-- 2. Alter the data types to use date for dates, varchar or char (for text) with size specified. 

ALTER TABLE clientv1
MODIFY COLUMN ClientNo VARCHAR(10),
MODIFY COLUMN FirstName VARCHAR(50),
MODIFY COLUMN MidName VARCHAR(50),
MODIFY COLUMN Surname VARCHAR(50),
MODIFY COLUMN Street VARCHAR(50),
MODIFY COLUMN City VARCHAR(50),
MODIFY COLUMN Zip VARCHAR(10),
MODIFY COLUMN Email VARCHAR(100),
MODIFY COLUMN MobileNo VARCHAR(20),
MODIFY COLUMN Landline VARCHAR(20),
MODIFY COLUMN CreditLimit DECIMAL(10,2);

ALTER TABLE detail
MODIFY COLUMN InvoiceNo INT,
MODIFY COLUMN ProdCode VARCHAR(10),
MODIFY COLUMN Quantity INT;

ALTER TABLE ordert
MODIFY COLUMN InvoiceNo INT,
MODIFY COLUMN ClientNo VARCHAR(10),
MODIFY COLUMN OrderDate DATE;

ALTER TABLE product
MODIFY COLUMN ProductCode VARCHAR(10),
MODIFY COLUMN ProductDescription VARCHAR(100),
MODIFY COLUMN UnitCost DECIMAL(10,2),
MODIFY COLUMN Category VARCHAR(50);